#server:
#  servlet:
#    context-path: /users

###
#   Database Settings
###

spring:
  application:
    name: template
  #########################################################################################################
  #   Datasource
  #########################################################################################################
  datasource:
    url: jdbc:h2:mem:users-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  #########################################################################################################
  #   JPA
  #########################################################################################################
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  #########################################################################################################
  #   H2 Settings
  #########################################################################################################
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

#########################################################################################################
#   Logging
#########################################################################################################
logging:
  file:
    path: C:/temp/logs

#########################################################################################################
#   Users app
#########################################################################################################
template-application:
  logging:
    format: JSON
    alertWarningMethodExecutionTime: 500 #in milliseconds
